# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8b99e9cfa48a1f668227bd48c8f38373c13e623552568814047728bffa93d4a5333cf7425d7fbf818302171490f86b1a17d857733818105cd6ff1f08d1385f

test:
  secret_key_base: 039d1d7406da9fda24c9f28cf3a4da440a8c922e5ec6133e2a90ac33b3a30d8ded87fbd761dc06a33f5722a9b38ee148cff6887b935d648f2d4b9495176e8139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
